apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kata-manager-binding
  namespace: sandbox-containers
subjects:
  - kind: ServiceAccount
    name: kata-manager
    namespace: default
roleRef:
  kind: Role
  name: kata-manager-role
  apiGroup: rbac.authorization.k8s.io
